FROM node:22

ARG DATABASE_URL
ARG JWT_SECRET_KEY
ARG PROD_CLIENT_URL
ARG WHATSAPP_API_URL
ARG WHATSAPP_API_KEY

ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV PROD_CLIENT_URL=$PROD_CLIENT_URL
ENV WHATSAPP_API_URL=$WHATSAPP_API_URL
ENV WHATSAPP_API_KEY=$WHATSAPP_API_KEY

COPY . /app

WORKDIR /app

RUN npm install --legacy-peer-deps

EXPOSE 8000

CMD ["npm", "start"]