FROM node:22

ARG DATABASE_URL
ARG JWT_SECRET_KEY
ARG PROD_CLIENT_URL

ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV PROD_CLIENT_URL=$PROD_CLIENT_URL

COPY . /app

WORKDIR /app

RUN npm install --legacy-peer-deps

EXPOSE 8000

CMD ["npm", "start"]