name: Backend Staging CD
on:
  push:
    branches:
      - staging
      - chore/Deployment
  workflow_dispatch:
    inputs:
      deploy_notes:
        description: "Notes about this deployment"
        required: false
        default: "Manual deployment"
      skip_migrations:
        description: "Skip database migrations"
        required: false
        default: false
        type: boolean
      reset_database:
        description: "Reset database (WARNING: ALL DATA WILL BE LOST)"
        required: false
        default: false
        type: boolean
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: |
          docker build -t inventum-backend:staging .
          
      - name: Run database migrations
        if: ${{ inputs.skip_migrations != true }}
        working-directory: /home/noov/inventum/staging
        run: |
          # Source the .env file to get environment variables
          source .env.staging
          
          # Start DB if not running
          if ! docker ps | grep -q inventum-mysql-staging; then
            docker compose -f docker-compose.staging.yml up -d db
            echo "Waiting for MySQL to initialize..."
            sleep 15
          fi
          
          # Reset database if requested
          if [ "${{ inputs.reset_database }}" == "true" ]; then
            echo "⚠️ RESETTING DATABASE - ALL DATA WILL BE LOST ⚠️"
            docker run --rm \
              --network inventum-network \
              -e DATABASE_URL="$DATABASE_URL" \
              inventum-backend:staging \
              npx prisma migrate reset --force
          else
            # Run regular migrations
            docker run --rm \
              --network inventum-network \
              -e DATABASE_URL="$DATABASE_URL" \
              inventum-backend:staging \
              npx prisma migrate deploy
          fi
          
      - name: Deploy backend
        working-directory: /home/noov/inventum/staging
        run: |
          # Stop and remove only the backend container if it exists
          docker compose -f docker-compose.staging.yml stop backend || true
          docker compose -f docker-compose.staging.yml rm -f backend || true
          
          # Start the backend container
          docker compose -f docker-compose.staging.yml up -d backend
      
      - name: Deployment Info
        run: |
          echo "Deployment completed with notes: ${{ github.event.inputs.deploy_notes || 'No notes provided' }}"
          if [ "${{ inputs.reset_database }}" == "true" ]; then
            echo "⚠️ DATABASE WAS RESET - ALL PREVIOUS DATA HAS BEEN LOST ⚠️"
          fi