name: Backend Staging CD
on:
  push:
    branches:
      - chore/Deployment
      - health
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build -t inventum-backend:staging .
      
      - name: Run database migrations
        working-directory: /home/noov/inventum/staging
        run: |
          # Source the .env file to get environment variables
          source .env
          
          # Start DB if not running
          if ! docker ps | grep -q inventum-mysql-staging; then
            docker compose -f docker-compose.staging.yml up -d db
            echo "Waiting for MySQL to initialize..."
            sleep 15
          fi
          
          # Run regular migrations
          docker run --rm \
            --network inventum-network \
            -e DATABASE_URL="$DATABASE_URL" \
            inventum-backend:staging \
            npx prisma migrate deploy
      
      - name: Deploy backend
        working-directory: /home/noov/inventum/staging
        run: |
          # Stop and remove only the backend container if it exists
          docker compose -f docker-compose.staging.yml stop backend || true
          docker compose -f docker-compose.staging.yml rm -f backend || true
          
          # Start the backend container
          docker compose -f docker-compose.staging.yml up -d backend
      
      - name: Deployment Info
        run: |
          echo "Deployment completed successfully"