name: Backend Staging CD
on:
  push:
    branches:
      - chore/Deployment
      - health
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build and Deploy Frontend
        working-directory: /home/noov/inventum/staging
        run: |
          # Load environment variables
          source .env
          
          # Create .env.local in the frontend source directory
          cat > /home/noov/actions-runner/_work/INVENTUM-FE/INVENTUM-FE/.env.local << EOF
          NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
          NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
          NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
          NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION}
          EOF
          
          # Verify the .env.local file
          echo "Created .env.local with:"
          cat /home/noov/actions-runner/_work/INVENTUM-FE/INVENTUM-FE/.env.local
          
          # Build the Docker image (Next.js will automatically read .env.local)
          docker build --no-cache -t inventum-frontend:staging /home/noov/actions-runner/_work/INVENTUM-FE/INVENTUM-FE/
          
          # Stop and redeploy frontend
          docker compose -f docker-compose.staging.yml stop frontend || true
          docker compose -f docker-compose.staging.yml rm -f frontend || true
          docker compose -f docker-compose.staging.yml up -d frontend
          
          # Clean up the .env.local file
          rm -f /home/noov/actions-runner/_work/INVENTUM-FE/INVENTUM-FE/.env.local
          
          # Wait and verify
          sleep 10
          echo "Deployment verification:"
          docker exec inventum-frontend-staging printenv | grep NEXT_PUBLIC
          
          echo "Frontend deployment completed successfully"