name: CI Pipeline

on:
  push:
    branches:
      - "*"
      - "chore/*" # Delete this later

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for .mdc files in .cursor/rules
        run: |
          if ! ls .cursor/rules/*.mdc 1> /dev/null 2>&1; then
            echo "❌ No .mdc files found in .cursor/rules. This might indicate AI-generated output without code rules."
            exit 1
          else
            echo "✅ .mdc files found in .cursor/rules."
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify your Node.js version
          cache: "npm"

      - name: Install dependencies
        run: npm ci # Using 'npm ci' instead of 'npm install' for more reliable CI builds

      - name: Run linting
        run: npm run lint

      - name: Run Jest tests with coverage
        run: npm run test -- --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=INVENTUM-BE
            -Dsonar.projectName=INVENTUM-BE
            -Dsonar.sources=src
            -Dsonar.tests=__tests__
            -Dsonar.verbose=true
            -Dsonar.test.inclusions=__tests__/**/*.test.tsx,__tests__/**/*.test.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/node_modules/**,**/coverage/**
            -Dsonar.exclusions=src/configs/**,src/**/__tests__/**,**/node_modules/**,**/docs/**,src/routes/metrics.route.ts,src/services/metrics.service.ts,src/middleware/metrics.middleware.ts
            -Dsonar.qualitygate.wait=true
            -Dsonar.scanner.skipSystemTruststore=true
