name: CI Pipeline

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests with coverage
        run: npm run test

      - name: Run SonarQube analysis
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=InventoryManagement-BE \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=api \
            -Dsonar.tests=api/__tests__ \
            -Dsonar.test.inclusions=api/__tests__/**/*.test.tsx \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.coverage.exclusions=**/*.test.tsx

